#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
# Add to .local/bin to PATH
PATH=$PATH:~/.local/bin

# Import Current Theme
DIR="$HOME/.config/hypr"
RASI="$DIR/rofi/launcher.rasi"

# Run

# rofi -show combi -modes combi -combi-modes "window,drun,run" -theme ${RASI}

rofi \
    -show drun \
	-theme ${RASI}
