#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

# WALLPAPER='/home/kay/.config/hypr/wallpapers/wallpaper.jpg'
# WALLPAPER='/home/kay/.config/hypr/wallpapers/wallpaper.jpg'
WALLPAPER='/home/kay/.config/hypr/wallpapers/wallpaper.jpg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
